name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          chmod +x test_pipper.sh
          ./test_pipper.sh
        working-directory: ${{ github.workspace }}

  docker:
    runs-on: ubuntu-latest
    needs: build  # Ensures tests pass before running Docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t pipper .

      - name: Run Pipper in Docker
        run: docker run --rm pipper pipper --help
